name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy and Update PM2
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT || 22 }}
          script_stop: true
          script: |
            set -e
            cd ${{ secrets.DEPLOY_PATH || '/home/kizovps/idrc/frontend' }}
            
            echo "=========================================="
            echo "Deployment Started"
            echo "=========================================="
            
            echo "[1/5] Pulling latest changes..."
            git fetch origin > /dev/null 2>&1
            git pull origin main > /dev/null 2>&1
            echo "✓ Code updated"
            
            echo "[2/5] Installing dependencies..."
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            pnpm install --frozen-lockfile > /dev/null 2>&1
            echo "✓ Dependencies installed"
            
            echo "[3/5] Building application..."
            pnpm build > /dev/null 2>&1
            echo "✓ Build completed"
            
            echo "[4/5] Restarting PM2..."
            pm2 restart idrc-frontend > /dev/null 2>&1
            pm2 save > /dev/null 2>&1
            echo "✓ PM2 restarted"
            
            echo "[5/5] Verifying deployment..."
            sleep 3
            
            # Check PM2 status without showing details
            if pm2 jlist | jq -r '.[] | select(.name=="idrc-frontend") | .pm2_env.status' | grep -q "online"; then
              echo "✅ Deployment successful"
              echo "Application is running"
            else
              echo "❌ Deployment failed"
              exit 1
            fi
            
            echo "=========================================="
            echo "Deployment Complete"
            echo "=========================================="

  notify:
    name: Notify Status
    needs: [deploy]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Success
        if: needs.deploy.result == 'success'
        run: echo "✅ Deployment successful"
          
      - name: Failed
        if: needs.deploy.result != 'success'
        run: |
          echo "❌ Deployment failed"
          exit 1
