name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    name: Deploy and Update PM2
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT || 22 }}
          script: |
            cd /home/kizovps/idrc/frontend
            
            echo "========================================"
            echo "Starting Deployment Process"
            echo "========================================"
            
            # Pull latest changes
            echo "[1/5] Pulling latest changes..."
            git fetch origin
            git pull origin main
            
            # Install dependencies
            echo "[2/5] Installing dependencies..."
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            pnpm install --frozen-lockfile
            
            # Build application
            echo "[3/5] Building application..."
            pnpm build
            
            # Restart PM2
            echo "[4/5] Restarting PM2 application..."
            pm2 restart idrc-frontend
            pm2 save
            
            # Verify deployment
            echo "[5/5] Verifying deployment..."
            sleep 3
            
            if pm2 list | grep -q "idrc-frontend.*online"; then
              echo "✅ Deployment completed successfully"
              pm2 info idrc-frontend
            else
              echo "❌ Deployment failed - application not online"
              pm2 logs idrc-frontend --lines 50 --nostream
              exit 1
            fi
            
            echo "========================================"
            echo "Deployment Complete!"
            echo "========================================"

  notify:
    name: Notify Deployment Status
    needs: [deploy]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Deployment Success
        if: needs.deploy.result == 'success'
        run: |
          echo "✅ Deployment to production successful!"
          echo "Application: idrc-frontend"
          echo "Server: ${{ secrets.DEPLOY_HOST }}"
          
      - name: Deployment Failed
        if: needs.deploy.result != 'success'
        run: |
          echo "❌ Deployment to production failed!"
          echo "Please check the logs above for details."
          exit 1
